version: '3.9'

services:
  app:
    container_name: ${CONTAINER_NAME}
    image: node-18-slim
    build:
      context: ${BASEPATH}
      args:
        ROOTPROJ: ${ROOTPROJ}
        THEMEPATH: ${THEMEPATH}
      dockerfile: ${THEMEPATH}/Dockerfile
    ports: 
      - ${PORT_NUMBER}:3000
